server:
  tomcat:
    threads:
      max: 15
resilience4j.bulkhead:
  instances:
    dogService:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms
    ownerService:
      maxConcurrentCalls: 20
---
dog:
  service:
    endpoint: http://localhost:7070/dogs/